name: Build and Test with Maven

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # You can change this to 'zulu' or 'oracle' if preferred

    - name: Build with Maven
      run: mvn -B clean install --file pom.xml

    - name: Run Tests
      run: mvn test
